### ISSUE TITLE
No distinction between course instances of same course.

### ISSUE THREAD

**Issue by zebala** [apluslms/mooc-jutut#2]
![screen shot 2017-09-21 at 19 24 54](https://user-images.githubusercontent.com/3922776/30706994-c64a6b12-9f02-11e7-8b72-cfb98edda8b0.png)

**Comment by jsorva** [comment]
I tried this now again after today’s meeting with EDIT, and the issue seems to be resolved since 2017 — the offerings between different years are distinguished from each other in the menu.

(At the meeting, I was also wondering why only a single instance of O1 was showing up for me in Jutut today. That seems to have something to do with which instances I had previously logged in on the server — two instances show up for me now, each labeled with its own year.)
