### ISSUE TITLE
Feedback "form content" search should not be affected by the order of the queried words

### ISSUE THREAD

**Issue by Mankro** [apluslms/mooc-jutut#33]
Request from the O1 2022 course, J.S.

I have just noticed something concerning.

In the filter feedback form, if I do Form Content search (in, say, Chapter 2.3) for the keywords
`Assign val var`
I find one of the feedback messages, which is — I think — the correct search result.

But if I instead search for
`val var Assign`
I get zero results.

So somehow the search cares about the order of the search terms, which is really unintuitive (and also pretty useless IMO).

I frequently rely on the Form Content search to find all instances of a particular term/topic. So if it’s unreliable, I’d like to know, and I’m also hoping for a fix very soon.

(Fortunately, it is not very common for me to use multiple search keywords at once. Still, I’m now thinking I must have made an assortment of errors in the past as a result of relying on the search.)

P.S. Here are two links to the results I mentioned:

`Assign val var`
https://jutut.cs.aalto.fi/manage/47/feedbacks/?path_key=w02_ch03&form_data=Assign+val+var+&order_by=-timestamp

`val var Assign`
https://jutut.cs.aalto.fi/manage/47/feedbacks/?path_key=w02_ch03&form_data=+val+var+Assign&order_by=-timestamp

Aalto internal ticket
https://rt.cs.aalto.fi/Ticket/Display.html?id=22001

**Comment by jsorva** [comment]
1. I would strongly prefer that to find all student-written messages that contain the substrings "var", "var", and "assign" somewhere, not necessarily as whole words.

2. I happened to use Assign there because I was testing if the weird results have something to do with case-sensitivity. I would prefer the search to be case-insensitive, which it is now, I believe.

BTW, I seem to recall that the "Form Content" now includes some other content beyond the textual answers. This makes searching for numerical values quite tricky. Maybe include just the textual answers? (Not related to this issue strictly; sorry.)
