### ISSUE TITLE
Sort the "Exercise" dropdown in the filtering view 

### ISSUE THREAD

**Issue by jsorva** [apluslms/mooc-jutut#43]
The items in the "Exercise" dropdown are now in arbitrary order, which makes the widget inconvenient to use.

**Comment by etanttila** [comment]
For the sorting, would it be desirable that there would always be a heading/grouping for each module (e.g. A bolded "Week 1" with the exercises nested underneath the heading with a small indentation? Or would it be better for all the exercises to be just listed in order without grouping?

Also, is it enough that the exercises would be sorted, or would it be wanted that there would be in input field for the module, where one selects the module/round/week, and the exercise selection is filtered based on this? This, of course, would be quite inconvenient if there is say, just one feedback exercise per week, but might be convenient if there are a ton of feedback exercises. Of course, it would be one more field filling up the filter view, and might be unnecessary when the ordering of the exercises is done (especially if contains grouping).

An idea that came to mind concerning the exercise dropdown:
Currently the dropdown allows one to select just one exercise at a time. Would it be a better (and needed) functionality (or needed) that one could select multiple exercises at a time? Or would it be inconvenient, as that would mean that one needs to unselect unwanted previous selections?
However, this might be more difficult to implement (and slower to process) due to how the API works. I suppose when issue #44 is fixed, it would help with seeing responses to several consecutive exercises.

**Comment by jsorva** [comment]
> probably a good initial fix is to just get the ordering in order

Agreed.

> Also, is it enough that the exercises would be sorted, or would it be wanted that there would be in input field for the module, where one selects the module/round/week, and the exercise selection is filtered based on this? This, of course, would be quite inconvenient if there is say, just one feedback exercise per week, but might be convenient if there are a ton of feedback exercises. Of course, it would be one more field filling up the filter view, and might be unnecessary when the ordering of the exercises is done (especially if contains grouping).

I, at least, have no need for this.

> An idea that came to mind concerning the exercise dropdown: Currently the dropdown allows one to select just one exercise at a time. Would it be a better (and needed) functionality (or needed) that one could select multiple exercises at a time?

A nice idea. I think this would be somewhat useful. But I would not consider this a high priority.
