### ISSUE TITLE
Include the chapter title in each message

### ISSUE THREAD

**Issue by jsorva** [apluslms/mooc-jutut#46]
For convenience while reading/browsing messages, perhaps it would be possible to include the module title (or part thereof) where we now have something like "1.7.15 |fi:Palaute|en:Feedback|/o1/w01_ch07_feedback". That would be much more informative in some (all?) cases. 

This must not increase the size of each message in the UI. On the contrary, it would be great if the screen estate for each message were reduced. (Not sure if there’s an issue for that.)

**Comment by etanttila** [comment]
If the feedback questionnaire is not embedded in an chapter but is rather on a page of it's own, what do we want to display instead of the chapter title? Do we want the "display name" of the exercise (e.g. "Palaute" or "1.7 Palaute" depending whether the exercises have the hierarchical number displayed for the course) or the "hierarchical name", which always includes the hierarcical number? Or the parent module name?
