### ISSUE TITLE
Upgrade Django to v4.2 LTS

### ISSUE THREAD

**Issue by Mankro** [apluslms/mooc-jutut#49]
Django v4.2 LTS has been released in April 2023. Django v3.2 reaches end of life in April 2024. Upgrade Django apps before the current version reaches end of life.

EOL schedule:
https://www.djangoproject.com/download/

Previous Django upgrade issue: #16

**Comment by etanttila** [comment]
MOOC-Jutut is dependent on several libraries, which at the moment are incompatible with Django 4 (at least due to the requirement of Django<4). I created issues for their update as well:

django-lti-login: https://github.com/apluslms/django-lti-login/issues/3
django-essentials: https://github.com/apluslms/django-essentials/issues/2
django-colortag: https://github.com/apluslms/django-colortag/issues/12
