### ISSUE TITLE
Chapter links are misleadingly labeled in the updated UI

### ISSUE THREAD

**Issue by jsorva** [apluslms/mooc-jutut#75]
This is a simple thing, but a bit complicated to explain...

Before this Friday’s update, for each feedback message in the Jutut teacher interface, a string was visible indication which chapter the feedback was from — below, I’ll call that the *source chapter* and the Jutut form embedded therein the *source form*. This string is very important, since it provides key information about what the student is talking about.

Before the update, there was no link from the message to the source chapter itself, however, as requested in #29. Moreover, the string was a path/ID (e.g., `w02/ch03_fi` or `wNN/intellij_en` or something like that) rather than the title of the source chapter, which would have been more user-friendly, which is something that came up in discussions this summer. 

Now, after the update, the situation is similar in that there is still no link to the source chapter—the link leads to a separate page with the source form only. Moreover, and more importantly still, that link is confusingly labeled; specifically, the link is labeled using A+’s internal IDs rather than something user-friendly. (I’ve already made multiple mistakes in the last 24h since the update as a consequence.) This is illustrated below. (And [here’s a link to the actual message in Jutut](https://jutut.cs.aalto.fi/manage/55/feedbacks/?student=3&exercise=2328).)

![image](https://github.com/apluslms/mooc-jutut/assets/8523129/fc97965e-cfc6-44eb-b16f-27eb04bcafac)

In the picture, the link is labeled _2.4.10 Feedback_. What appears to be the "chapter number" 2.4 is misleading — the link leads to the source form at the end of Chapter ***2.3*** (which, as it happens, is  technically the fourth component within Week 2 of O1, hence the A+ internal id of 2.4). The consequence of this is that the feedback-reading teacher will not realize what the student is actually referring to — unless one remembers constantly to do some off-by-one mental processing. (And one doesn’t.)

(Also, the number 10 and the word "Feedback" are unneeded in that label.)

As I noted, I think the chapter title would be best—_Chapter 2.3: Classes of Objects_—in this case). Failing that, even the old label (path) would be better.

I hope this can be patched soon. 🤞

**Comment by Mankro** [comment]
This is not a bug in the source code. The titles were changed in the summer update like you requested. However, what is missing is the data in the database. On existing courses, the new fields that have been added to the exercise model are empty. The fields must be filled in with the correct data so that the user interface renders the expected new titles for the feedback messages.

We will fill in the missing data to the database in the production server. If you started a new course now after the server upgrade, the data in the new course would be set up correctly for the new features. We didn't realize that old courses would be missing the data for the new fields after the server upgrade. ("Old course" = created before the server upgrade)

**Comment by Mankro** [comment]
@jsorva in the server, we fixed this for O1 2023. Other courses can wait until tomorrow.

**Comment by jsorva** [comment]
> @jsorva in the server, we fixed this for O1 2023. Other courses can wait until tomorrow.

Lovely! It’s already helped me!

**Comment by Mankro** [comment]
`exercise.parent_name` has been fixed in the jutut.cs server. That is, the attribute value has been updated for exercises that existed in the database before the version 2.6 upgrade.
